name: "IndexNow"
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,12 * * *'
jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: submit-to-bing
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: "https://jgacg.cc/sitemap.xml"
          endpoint: "www.bing.com"
          limit: 100
          key: ${{ secrets.INDEXNOW_KEY }}
          key-location: ${{ secrets.INDEXNOW_KEY_LOCATION }}
